{
    'name': 'Service Traiteur',
    'version': '18.0.1.0.0',
    'category': 'DIGIFAZ',
    'summary': 'Service traiteur avec portail web de demandes de prestations',
    'author': 'Restaurant des Lagunes',
    'depends': [
        'base', 'mail', 'sale_management', 'web', 'website',
        'lagunes_cantine',
        'lagunes_market',
    ],
    'data': [
        'security/lagunes_traiteur_security.xml',
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'data/type_prestation_data.xml',
        'data/logistique_data.xml',
        'data/cron_data.xml',

        'report/report_traiteur_devis.xml',
        'report/report_traiteur_logistique.xml',
        'report/report_traiteur_production_consolidated.xml',
        'report/report_traiteur_menu_proposition.xml',
        'report/report_traiteur_proposition_menu.xml',
        'report/report_invoice_inherit.xml',

        'views/lagunes_traiteur_type_prestation_views.xml',
        'views/lagunes_traiteur_niveau_views.xml',
        'views/lagunes_traiteur_logistique_views.xml',
        'views/lagunes_traiteur_proposition_views.xml',
        'views/lagunes_traiteur_demande_views.xml',
        'views/lagunes_traiteur_devis_views.xml',
        'views/lagunes_traiteur_config_views.xml',
        'views/lagunes_traiteur_dashboard_views.xml',
        'views/sale_order_views.xml',
        'wizard/lagunes_traiteur_production_wizard_views.xml',
        'views/lagunes_traiteur_menus.xml',
        'data/mail_template_data.xml',
        'views/website_traiteur_home.xml',
        'views/website_traiteur_wizard.xml',
        'views/website_traiteur_confirmation.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'lagunes_traiteur/static/src/css/traiteur_portail.css',
            'lagunes_traiteur/static/src/css/traiteur_style.css',
            'lagunes_traiteur/static/src/js/traiteur_wizard.js',
        ],
        'web.assets_backend': [
            'lagunes_traiteur/static/src/css/traiteur_backend.css',
            'lagunes_traiteur/static/src/xml/traiteur_dashboard_templates.xml',
            'lagunes_traiteur/static/src/js/traiteur_dashboard.js',
        ],
    },
    'demo': [
        'demo/demo_config.xml',
        'demo/demo_niveaux.xml',
        'demo/demo_demandes.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}