# -*- coding: utf-8 -*-
from . import lagunes_traiteur_demande
from . import lagunes_traiteur_demande_jour
from . import lagunes_traiteur_demande_prestation
from . import lagunes_traiteur_demande_plat
from . import lagunes_traiteur_niveau
from . import lagunes_traiteur_niveau_prix
from . import lagunes_traiteur_niveau_ligne
from . import lagunes_traiteur_type_prestation
from . import lagunes_traiteur_logistique
from . import lagunes_traiteur_logistique_line
from . import lagunes_traiteur_devis
from . import lagunes_traiteur_config
from . import lagunes_traiteur_dashboard
from . import lagunes_traiteur_proposition
from . import lagunes_traiteur_proposition_line
from . import mail_compose_message
from . import sale_order
from . import ir_actions_report
